image:
  name: hashicorp/terraform:0.14.10
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - apk add curl



stages:
  - validate
  - plan
  - apply
  - destroy

validate:
  stage: validate
  script:
    - rm -rf .terraform
    - terraform --version
    - terraform init
    - terraform validate

plan:
  stage: plan
  script:
    - rm -rf .terraform
    - terraform --version
    - terraform init
    - terraform plan
  dependencies:
    - validate

apply:
  stage: apply
  script:
    - rm -rf .terraform
    - terraform --version
    - terraform init
    - terraform apply --auto-approve
  dependencies:
    - plan

destroy:
    stage: destroy
    script:
      - rm -rf .terraform
      - terraform --version
      - terraform init
      - terraform state rm module.notejam_deployment module.rke-cluster module.rancher_server  module.downstream-custom-cluster module.downstream-rke-template || echo "partial run"
      - terraform destroy -force
    when: manual
    allow_failure: true

